# Generated by Django 2.0.3 on 2018-06-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=100, verbose_name='拼写')),
                ('meaning', models.CharField(max_length=300, verbose_name='解释')),
                ('mp3_url', models.URLField(blank=True, verbose_name='mp3')),
            ],
            options={
                'verbose_name_plural': '单词',
                'verbose_name': '单词',
            },
        ),
        migrations.CreateModel(
            name='WordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='书名')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('word_num', models.IntegerField(default=1000, verbose_name='单词数')),
                ('uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='上传人')),
            ],
            options={
                'verbose_name_plural': '单词本',
                'verbose_name': '单词本',
            },
        ),
        migrations.CreateModel(
            name='WordInUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_order', models.IntegerField(default=1, verbose_name='顺序')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learn.Word', verbose_name='单词')),
            ],
            options={
                'verbose_name_plural': '单元单词',
                'verbose_name': '单元单词',
            },
        ),
        migrations.CreateModel(
            name='WordUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_order', models.IntegerField(default=1, verbose_name='顺序')),
                ('word_num', models.IntegerField(default=2000, verbose_name='单词数')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordBook', verbose_name='单词本')),
            ],
            options={
                'verbose_name_plural': '单元',
                'verbose_name': '单元',
            },
        ),
        migrations.AddField(
            model_name='wordinunit',
            name='wordunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordUnit', verbose_name='单元'),
        ),
    ]
