# Generated by Django 2.0.3 on 2018-06-24 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0002_auto_20180618_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordBook', verbose_name='单词本')),
            ],
            options={
                'verbose_name_plural': '学习计划',
                'verbose_name': '学习计划',
            },
        ),
    ]
