# Generated by Django 2.0.3 on 2018-06-25 16:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0003_learningplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islearning', models.IntegerField(default=0, verbose_name='正在学习')),
                ('learn_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='学习时间')),
                ('duration', models.IntegerField(default=0, verbose_name='学习时长')),
                ('correct_rate', models.IntegerField(default=100, verbose_name='正确率')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.WordBook', verbose_name='单词本')),
            ],
            options={
                'verbose_name_plural': '学习记录',
                'verbose_name': '学习记录',
            },
        ),
    ]
