# Generated by Django 2.0.3 on 2018-06-26 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0004_learningrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyword', models.IntegerField(default=50, verbose_name='每日学习量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户设置',
                'verbose_name': '用户设置',
            },
        ),
        migrations.AddField(
            model_name='learningplan',
            name='haslearned',
            field=models.IntegerField(default=0, verbose_name='已学习'),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='haslearned',
            field=models.IntegerField(default=0, verbose_name='已经学习'),
        ),
    ]
