# Generated by Django 2.0.3 on 2018-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20180626_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='learntype',
            field=models.IntegerField(default=0, verbose_name='单词的目标掌握程度'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='showmeaning',
            field=models.IntegerField(default=1, verbose_name='英文解释'),
        ),
    ]
