# Generated by Django 2.0.3 on 2018-06-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20180627_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningplan',
            name='haslearned',
        ),
    ]
