# Generated by Django 2.0.3 on 2018-06-29 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0008_auto_20180628_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learn.Word', verbose_name='单词')),
            ],
            options={
                'verbose_name_plural': '用户自定义单词',
                'verbose_name': '用户自定义单词',
            },
        ),
    ]
